### ISSUE TITLE
There are semi in comments in .less, format will output "Unknown word"

### ISSUE THREAD

**Issue by lcysgsg** [prettier/prettier-vscode#1942]
### Summary

There are semi in comments in .less, format will output "Unknown word". Remove semi will get `Formatting completed`.

But same code in the [prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKB6DACAAgSwFsAHCAJxmwHIA-AQ1gBMNH8BnGDBmRgOgBs4bNlQDc2bFmyBUfUCmioAztQJ2mgBeNA2fKAQt2yDh2QOwWgeH1ZgY+VA4aaA3uXTpeAIwDm2YOgkALOPlvOYSbAEYADH4Abs6iTtgQgXBkAGb8EADu3s74jIwIoVAS1nRgANa2ZBAArlCM3kVk-AAUvLxcwnAwbBh2vABWxLYAlNhQEAC0ZHDEcHQwGVk5+YUljP1s+ABecN6QkWQZAL6WmDgEJOSUVHUAymD4CGBwADJ0AJ7FMAAqroRwAkIiGVKeMMRsSCwxEKvG4vDSC1smEYEDAzQ4d0E-TAUAAxABSACiAA50QBBABs6OxRMxAHZ0QBOABCVNJFOptOxABYsazGejqaSiXi-JyKZiAKycgDCxIAYjt0EhbHFsvwHGFQbBkXQyIxFZkJNhsnkCsVSt4YGQGGxiGqEJQAIREUgUbiiazkNJkfrxFIwZzeHzEAAeEx1zqiyIgcTI3jItmsVR8ACYyQAaXzYgDMSdjgsFXQDTvVwYRgm8bFDKRzQddJtYRQB2AJfpzU31sxDYYjUboMfjSZ8qfTmaTfl4fjJ2OzYSdvvmzjoMMS2HwUDYjWwfj9K7XPjrvuwzLXkeyncTybT2AzgoHvGZWYD2ygmxACZAEGIMHw0DYyFAasK8QAChbF2QEA6H4eJ7g-R9rBNPJGhOc1zigWxkGNIo4EfOBCGsOBUmw25EKKOhbDgcVyEIMZX0QoC6CKGAIAfEBPEIfgAHVkngM0cjgE4EAWV9AnwGA7iAuEIJABclwoX8TVsMjkGiECl0fNo2F9aloNyWC6Dea4FzgOSFLQkBlN9E4F1lOAAEUiggeB9P4RSQHNMgJKA7RROBBcYGYj1nGQbE-EfYEICXZiTWIIDgSEKJInogBHaz4Ck58PxQOg2H6KA4Gw7D6KGeL8CGKTCNkpB5Pswyl0IfBkLIVDHwWRDBCsmy9NKgzHxgOhrG8xhPWQWMOpNfB+DMkUIEIEqQCEQV6OrOAni6lKyocwJUIASVKS0zjIfAXzxUoTkEwQ7KXTZNiAA)  is ok.

### Github Repository to Reproduce Issue

```less
// @import '~antd/dist/antd.less';  

.bg {
  height: 100vh;
  overflow: hidden;
  background: url(../assets/bg.jpg) no-repeat;
  background-size: cover;
}
// @import './ScienceLayoutTheme.less';
// https://pro.ant.design/docs/style-cn#%E8%A6%86%E7%9B%96%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F
:global {
  .ant-card {
    background: transparent !important;border-width: 1px;
  border-color: rgb(127, 183, 255);
  border-style: solid;
  border-radius: 6px;
  background-color: rgba(127, 183, 255, 0.078);
  box-shadow: inset 0px 0px 16px 4px rgba(127, 183, 255, 0.45);
  }
}
```

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information
 
> Prettier: ^2.0.1
> VSCode: 
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

## Prettier Log Output

```
["INFO" - 上午9:41:33] Formatting c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\src\layouts\ScienceLayout.less
["INFO" - 上午9:41:33] Using config file at 'c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\.prettierrc.js'
["INFO" - 上午9:41:33] Using ignore file (if present) at c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\.prettierignore
["INFO" - 上午9:41:33] File Info:
{
  "ignored": false,
  "inferredParser": "less"
}
["INFO" - 上午9:41:33] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 上午9:41:33] Prettier Options:
{
  "filepath": "c:\\Users\\lcysgsg\\ZhiDian\\code\\PeiWangDaiDian\\Management\\src\\layouts\\ScienceLayout.less",
  "parser": "less",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "singleQuote": true,
  "trailingComma": "all",
  "printWidth": 100,
  "proseWrap": "never"
}
["ERROR" - 上午9:41:33] Error formatting document.
CssSyntaxError: <css input>:10:1: Unknown word
	at Input.error (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\postcss\lib\input.js:128:16)
	at Parser.unknownWord (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\postcss\lib\parser.js:561:22)
	at Parser.other (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\postcss\lib\parser.js:166:12)
	at Parser.parse (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\postcss\lib\parser.js:75:16)
	at parse (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\postcss\lib\parse.js:17:12)
	at new LazyResult (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\postcss\lib\lazy-result.js:64:16)
	at Processor.<anonymous> (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\postcss\lib\processor.js:142:12)
	at Processor.process (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\postcss\lib\processor.js:121:23)
	at module.exports (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\prettier-plugin-style-order\src\config\sorter.js:8:6)
	at Object.preprocess (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\prettier-plugin-style-order\src\index.js:40:18)
	at Object.parse (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\prettier\index.js:13620:21)
	at coreFormat (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\prettier\index.js:14899:14)
	at format (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\prettier\index.js:15131:14)
	at c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\prettier\index.js:57542:12
	at Object.format (c:\Users\lcysgsg\ZhiDian\code\PeiWangDaiDian\Management\node_modules\prettier\index.js:57562:12)
	at t.default.<anonymous> (c:\Users\lcysgsg\.vscode\extensions\esbenp.prettier-vscode-6.3.2\dist\extension.js:1:16897)
	at Generator.next (<anonymous>)
	at s (c:\Users\lcysgsg\.vscode\extensions\esbenp.prettier-vscode-6.3.2\dist\extension.js:1:9119)
["INFO" - 上午9:41:33] Formatting completed in 23.5135ms.
```
