### ISSUE TITLE
Extension 'Prettier - Code formatter' is configured as formatter but it cannot format 'Astro'-files

### ISSUE THREAD

**Issue by testersen** [prettier/prettier-vscode#3247]
When `editor.formatOnSave` is enabled and I save an astro file, nothing happens.

When I use the `Format Document` command I the error I put as title: `Extension 'Prettier - Code formatter' is configured as formatter but it cannot format 'Astro'-files`.

When I use the `Format Document (Forced)` command it works.

Expected result, format on save option should work along with the `Format Document` command.

### Versions

```toml
# VS Code Extensions
esbenp.prettier-vscode = "10.1.0"
astro-build.astro-vscode = "2.5.4"

# package.json
prettier = "3.1.1"
prettier-plugin-astro = "0.12.2"
```

#### VS Code
```
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:16.874Z (1 wk ago)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```
