### ISSUE TITLE
Read/use version and config from `.pre-commit-config.yaml`

### ISSUE THREAD

**Issue by fregante** [prettier/prettier-vscode#3280]
**Is your feature request related to a problem? Please describe.**

This plugin uses the local or global version of Prettier, but there are additional projects that use Prettier as part of git or other tools. One of them is https://pre-commit.com/, which defines the version of Prettier in a config file that looks like:

```yml
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
```

**Describe the solution you'd like**

It would be nice for prettier-vscode to automatically read this config/version used by pre-commit

**Describe alternatives you've considered**

I'd have to add an extra dev dependency to my repo and ensure it's kept up to date with `pre-commit-config.yml`

I think this other issue has other use cases too:

- https://github.com/prettier/prettier-vscode/issues/2828

**Additional context**

It was also asked on StackOverflow: https://stackoverflow.com/q/69449987/288906
