### ISSUE TITLE
Problem with `grid-template` shorthand of CSS Grid Layout.

### ISSUE THREAD

**Issue by alxmcr** [prettier/prettier-vscode#406]
## Information Technical

| Tools        | Version            |
| ------------- |:-------------:| 
| VS Code      | 1.21.1 |
| Prettier - Code formatter      | 1.2.2      | 

Hi everyone 🙂, 

I'm working with **CSS Grid Layout** mainly with the `grid-template` shorthand. Unfortunately, I have some problems with **Prettier** in my code:

- **semi-colon expected** - Screenshoot

![semi-colon expected](https://image.ibb.co/nj44aS/2_error_message_prettier.png)

**Section Main of CSS Code**

If you would like to watch the complete code in CodePen. The link is: [Complete Example](https://codepen.io/maurroj/pen/VXyMXE) 

```css
/* GRID Container */
main {
    height: 100vh;
    display: grid;
    grid-gap: 10px;
    font-family: sans-serif;
        
    /* Shorthand 'grid-template' */
    grid-template: 
    [ini] 'header header header' 1fr
    [contenido-start] 'left1 info right1' 1fr
    'left1 info right2' 1fr
    'left1 footer footer' 1fr [end]
    / 
    [ini] 1fr [info-start] 2fr 1fr [end];    
}
```

I did many attempts:

1. `/* prettier-ignore */` 

I saw [#2703](https://github.com/prettier/prettier/issues/2703)

![semi-colon expected](https://image.ibb.co/kyMT27/3_try_1.png)

2. Put in the same line 

![semi-colon expected](https://image.ibb.co/mdYVFS/5_try_3.png)

But, the problem **continued**.

Please, Can you help me to resolve this problem? I would appreciate your help 🙂. I don't know, How Can I resolve it?

Corrections or comments are completely welcome. Have a nice day!
