### ISSUE TITLE
Prettier formats YAML incorrectly

### ISSUE THREAD

**Issue by peterj** [prettier/prettier-vscode#560]
Prettier appends `?` to YAML in VS Code. For example, paste the following into a .yaml file in VSCode:

```yaml
kind: checknothing
metadata:
    name: greeter-svc-request
spec:

```

Now save the document and Prettier will auto-format it to:

```
kind: checknothing
metadata:
    name: greeter-svc-request
? spec

```

I am using VS Code 1.26.1 and Prettier for VSCode 1.6.1. I verified that after adding: `    "prettier.disableLanguages": ["yaml"]` to settings, the issue doesn't repro anymore.
