### ISSUE TITLE
Indent broken for css multi-line code

### ISSUE THREAD

**Issue by GrimLink** [prettier/prettier-vscode#715]
When using formatting in vscode (1.30.2) with prettier-vscode (v1.8.0).
And with the following setting set;

```JSON
{
  "prettier.stylelintIntegration": true,
  "prettier.eslintIntegration": true
}
```

My css styles that are multi-line are given a wrong indent.

```CSS
.styles {
  background-image:
 linear-gradient(
    30deg,
    rgba(247, 251, 254, 1) 0%,
    rgba(221, 226, 232, 1) 100%
  );
  box-shadow:
 inset 0 2px 7px 1px rgba(255, 255, 255, .5),
    inset 0 -5px 20px rgba(187, 200, 225, .35),
    0 2px 6px rgba(40, 39, 66, .14),
 0 10px 20px rgba(40, 39, 66, .06),
    76px 75px 169px -35px rgba(0, 0, 0, .4);
}
```
