### ISSUE TITLE
extension can not work when the file has grammatical mistake

### ISSUE THREAD

**Issue by TreeZhou** [prettier/prettier-vscode#739]
extension can not work when the file has grammatical mistake，
like the following mistake
```css
.ddss-dd {
                width: 10px,
     width: 10px;
}
```
<img width="176" alt="2019-02-28 5 55 36" src="https://user-images.githubusercontent.com/32838069/53557985-1411aa00-3b82-11e9-97be-a331a23a06ab.png">

But extension called Beautify can work normally  in the same case conditions
