### ISSUE TITLE
Less mixin weird behavior

### ISSUE THREAD

**Issue by incompletude** [prettier/prettier-vscode#809]
I have a set of media mixins like this:

```less
@media-mobile: ~'(min-width:' @size-mobile ~')';

.on-mobile(@rules) {
  @media @media-mobile {
    @rules();
  }
}
```

I use them inside `.vue` files:

```
<template>
  <h1>Hello world!</h1>
</template>

<style lang="less">
body {
  background-color: gold;

  .on-desktop(
    {background-color: lightgray; border-color: red;}
  );
}
</style>
```

Expected formatting:

```
  .on-desktop({
    background-color: lightgray;
    border-color: red;
  });
```

I tried outside a vue context and found the same behaviour.
